
name: Java CI with Gradle

on:
  push:
    branches: [ master ]

jobs:
  buildv8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  buildv9:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up java 9
      uses: actions/setup-java@v1
      with:
        java-version: 9
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  buildv10:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up java 10
      uses: actions/setup-java@v1
      with:
        java-version: 10
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  buildv11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  buildv12:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up java 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  buildv13:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up java 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  buildv14:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up java 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  buildv15:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up java 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
